### ISSUE TITLE
화면 비율 설정 오류

### ISSUE THREAD

**Issue by ChaeryungYoon** [Sminp/Softwareengineering#13]
설정창에서 화면 비율 변경 시도 시 아무런 이벤트가 발생하지 않음

if event.type == pygame.MOUSEBUTTONUP:
                    mouse_pos = pygame.mouse.get_pos()
                    if sizefull_button.get_rect().collidepoint(mouse_pos):
                        screen_size(2)
                    elif size16_button.get_rect().collidepoint(mouse_pos):
                        screen_size(1)

**Comment by Sminp** [comment]
일단 함수 실행이 안되는걸로 해봐
아 그리고 고쳤다
self.rect.center = self.position
